### ISSUE TITLE
React-Dom Typings command doesnt work.

### ISSUE THREAD

**Issue by bleevo** [ServiceStackApps/typescript-redux#4]
typings install react-dom --ambient --save
typings ERR! message Unable to find "react-dom" in the registry. If you can contribute this type definition, please help us: https://github.com/typings/registry

Related: typings/typings#256

Work around: typings install --ambient --save github:DefinitelyTyped/DefinitelyTyped/react/react-dom.d.ts

**Comment by bleevo** [comment]
Related: https://github.com/typings/typings/issues/256

**Comment by mythz** [comment]
Hi, thx for the heads up, I've added a note about the workaround in this commit: https://github.com/ServiceStackApps/typescript-redux/commit/63fa2a64e4ec4a31692af8fba691e843ea630961

**Comment by blakeembrey** [comment]
This has been fixed. Changes in the indexing have been implemented to detect the DefinitelyTyped structure of `<name>/<name>-<suffix>.d.ts`.

**Comment by mythz** [comment]
@blakeembrey perfect, appreciate the update!

**Comment by josersleal** [comment]
somehow still does not work
ever heard of testing?... 

typings install react-dom
typings ERR! message Unable to find "react-dom" ("npm") in the registry. Did you
 want to try searching another source? Also, if you want contribute these typing
s, please help us: https://github.com/typings/registry
typings ERR! caused by https://api.typings.org/entries/npm/react-dom/versions/la
test responded with 404, expected it to equal 200

typings ERR! cwd path
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "node" "*\npm\node_m
odules\typings\dist\bin.js" "install" "react-dom"
typings ERR! node -v v0.12.6
typings ERR! typings -v 1.0.4

typings ERR! If you need help, you may report this error at:
typings ERR!   https://github.com/typings/typings/issues

**Comment by blakeembrey** [comment]
@josersleal I'm not sure who you're talking to, but yes, I'm sure we're all heard of testing. Maybe you want to read the documentation? https://github.com/typings/typings#updating-from-0x-to-10

**Comment by blakeembrey** [comment]
It just looks like the documentation in this repo is out of date. I'm sure the author would appreciate if you made a PR.

**Comment by josersleal** [comment]
Yes.. I was trying to be funny... ust like you ;)

I tried the dt comand and it works

**Comment by blakeembrey** [comment]
@josersleal Awesome, good to hear 😄 Tone is hard on the internet, sometimes it doesn't come across like that.
